// Code generated by protoc-gen-go. DO NOT EDIT.
// source: map.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetBusesLocationRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBusesLocationRequest) Reset()         { *m = GetBusesLocationRequest{} }
func (m *GetBusesLocationRequest) String() string { return proto.CompactTextString(m) }
func (*GetBusesLocationRequest) ProtoMessage()    {}
func (*GetBusesLocationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_map_8cc682c73c2d57ea, []int{0}
}
func (m *GetBusesLocationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBusesLocationRequest.Unmarshal(m, b)
}
func (m *GetBusesLocationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBusesLocationRequest.Marshal(b, m, deterministic)
}
func (dst *GetBusesLocationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBusesLocationRequest.Merge(dst, src)
}
func (m *GetBusesLocationRequest) XXX_Size() int {
	return xxx_messageInfo_GetBusesLocationRequest.Size(m)
}
func (m *GetBusesLocationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBusesLocationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBusesLocationRequest proto.InternalMessageInfo

type GetBusesLocationResponse struct {
	BusesLocation        []*GetBusesLocationResponse_BusLocation `protobuf:"bytes,1,rep,name=buses_location,json=busesLocation,proto3" json:"buses_location,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                `json:"-"`
	XXX_unrecognized     []byte                                  `json:"-"`
	XXX_sizecache        int32                                   `json:"-"`
}

func (m *GetBusesLocationResponse) Reset()         { *m = GetBusesLocationResponse{} }
func (m *GetBusesLocationResponse) String() string { return proto.CompactTextString(m) }
func (*GetBusesLocationResponse) ProtoMessage()    {}
func (*GetBusesLocationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_map_8cc682c73c2d57ea, []int{1}
}
func (m *GetBusesLocationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBusesLocationResponse.Unmarshal(m, b)
}
func (m *GetBusesLocationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBusesLocationResponse.Marshal(b, m, deterministic)
}
func (dst *GetBusesLocationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBusesLocationResponse.Merge(dst, src)
}
func (m *GetBusesLocationResponse) XXX_Size() int {
	return xxx_messageInfo_GetBusesLocationResponse.Size(m)
}
func (m *GetBusesLocationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBusesLocationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetBusesLocationResponse proto.InternalMessageInfo

func (m *GetBusesLocationResponse) GetBusesLocation() []*GetBusesLocationResponse_BusLocation {
	if m != nil {
		return m.BusesLocation
	}
	return nil
}

type GetBusesLocationResponse_BusLocation struct {
	Unit                 string   `protobuf:"bytes,1,opt,name=unit,proto3" json:"unit,omitempty"`
	Timestamp            string   `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Coordinate           *LatLng  `protobuf:"bytes,3,opt,name=coordinate,proto3" json:"coordinate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBusesLocationResponse_BusLocation) Reset()         { *m = GetBusesLocationResponse_BusLocation{} }
func (m *GetBusesLocationResponse_BusLocation) String() string { return proto.CompactTextString(m) }
func (*GetBusesLocationResponse_BusLocation) ProtoMessage()    {}
func (*GetBusesLocationResponse_BusLocation) Descriptor() ([]byte, []int) {
	return fileDescriptor_map_8cc682c73c2d57ea, []int{1, 0}
}
func (m *GetBusesLocationResponse_BusLocation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBusesLocationResponse_BusLocation.Unmarshal(m, b)
}
func (m *GetBusesLocationResponse_BusLocation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBusesLocationResponse_BusLocation.Marshal(b, m, deterministic)
}
func (dst *GetBusesLocationResponse_BusLocation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBusesLocationResponse_BusLocation.Merge(dst, src)
}
func (m *GetBusesLocationResponse_BusLocation) XXX_Size() int {
	return xxx_messageInfo_GetBusesLocationResponse_BusLocation.Size(m)
}
func (m *GetBusesLocationResponse_BusLocation) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBusesLocationResponse_BusLocation.DiscardUnknown(m)
}

var xxx_messageInfo_GetBusesLocationResponse_BusLocation proto.InternalMessageInfo

func (m *GetBusesLocationResponse_BusLocation) GetUnit() string {
	if m != nil {
		return m.Unit
	}
	return ""
}

func (m *GetBusesLocationResponse_BusLocation) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func (m *GetBusesLocationResponse_BusLocation) GetCoordinate() *LatLng {
	if m != nil {
		return m.Coordinate
	}
	return nil
}

// An object representing a latitude/longitude pair. This is expressed as a pair
// of doubles representing degrees latitude and degrees longitude. Unless
// specified otherwise, this must conform to the
// <a href="http://www.unoosa.org/pdf/icg/2012/template/WGS_84.pdf">WGS84
// standard</a>. Values must be within normalized ranges.
type LatLng struct {
	// The latitude in degrees. It must be in the range [-90.0, +90.0].
	Latitude float64 `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	// The longitude in degrees. It must be in the range [-180.0, +180.0].
	Longitude            float64  `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LatLng) Reset()         { *m = LatLng{} }
func (m *LatLng) String() string { return proto.CompactTextString(m) }
func (*LatLng) ProtoMessage()    {}
func (*LatLng) Descriptor() ([]byte, []int) {
	return fileDescriptor_map_8cc682c73c2d57ea, []int{2}
}
func (m *LatLng) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LatLng.Unmarshal(m, b)
}
func (m *LatLng) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LatLng.Marshal(b, m, deterministic)
}
func (dst *LatLng) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LatLng.Merge(dst, src)
}
func (m *LatLng) XXX_Size() int {
	return xxx_messageInfo_LatLng.Size(m)
}
func (m *LatLng) XXX_DiscardUnknown() {
	xxx_messageInfo_LatLng.DiscardUnknown(m)
}

var xxx_messageInfo_LatLng proto.InternalMessageInfo

func (m *LatLng) GetLatitude() float64 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *LatLng) GetLongitude() float64 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func init() {
	proto.RegisterType((*GetBusesLocationRequest)(nil), "proto.GetBusesLocationRequest")
	proto.RegisterType((*GetBusesLocationResponse)(nil), "proto.GetBusesLocationResponse")
	proto.RegisterType((*GetBusesLocationResponse_BusLocation)(nil), "proto.GetBusesLocationResponse.BusLocation")
	proto.RegisterType((*LatLng)(nil), "proto.LatLng")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MapClient is the client API for Map service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MapClient interface {
	GetBusesLocation(ctx context.Context, in *GetBusesLocationRequest, opts ...grpc.CallOption) (*GetBusesLocationResponse, error)
}

type mapClient struct {
	cc *grpc.ClientConn
}

func NewMapClient(cc *grpc.ClientConn) MapClient {
	return &mapClient{cc}
}

func (c *mapClient) GetBusesLocation(ctx context.Context, in *GetBusesLocationRequest, opts ...grpc.CallOption) (*GetBusesLocationResponse, error) {
	out := new(GetBusesLocationResponse)
	err := c.cc.Invoke(ctx, "/proto.Map/GetBusesLocation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MapServer is the server API for Map service.
type MapServer interface {
	GetBusesLocation(context.Context, *GetBusesLocationRequest) (*GetBusesLocationResponse, error)
}

func RegisterMapServer(s *grpc.Server, srv MapServer) {
	s.RegisterService(&_Map_serviceDesc, srv)
}

func _Map_GetBusesLocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBusesLocationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MapServer).GetBusesLocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Map/GetBusesLocation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MapServer).GetBusesLocation(ctx, req.(*GetBusesLocationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Map_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Map",
	HandlerType: (*MapServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBusesLocation",
			Handler:    _Map_GetBusesLocation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "map.proto",
}

func init() { proto.RegisterFile("map.proto", fileDescriptor_map_8cc682c73c2d57ea) }

var fileDescriptor_map_8cc682c73c2d57ea = []byte{
	// 249 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x90, 0x41, 0x4b, 0xc4, 0x30,
	0x10, 0x85, 0xcd, 0xae, 0x2e, 0x76, 0xca, 0x8a, 0xcc, 0xc5, 0x58, 0x44, 0x4b, 0x4f, 0x05, 0xb1,
	0x87, 0xfa, 0x0f, 0x7a, 0xf1, 0x52, 0x2f, 0x01, 0x6f, 0x82, 0xa4, 0xbb, 0x61, 0x09, 0xb4, 0x49,
	0xdc, 0x4c, 0xfe, 0xae, 0xbf, 0x45, 0x36, 0x5d, 0x6c, 0x51, 0x16, 0x4f, 0x49, 0xde, 0xf7, 0x92,
	0x97, 0x79, 0x90, 0x0c, 0xd2, 0x55, 0x6e, 0x6f, 0xc9, 0xe2, 0x45, 0x5c, 0x8a, 0x5b, 0xb8, 0x79,
	0x51, 0xd4, 0x04, 0xaf, 0x7c, 0x6b, 0x37, 0x92, 0xb4, 0x35, 0x42, 0x7d, 0x06, 0xe5, 0xa9, 0xf8,
	0x62, 0xc0, 0xff, 0x32, 0xef, 0xac, 0xf1, 0x0a, 0x05, 0x5c, 0x75, 0x07, 0xf0, 0xd1, 0x1f, 0x09,
	0x67, 0xf9, 0xb2, 0x4c, 0xeb, 0xc7, 0xf1, 0xf9, 0xea, 0xd4, 0xc5, 0xaa, 0x09, 0x93, 0xb6, 0xee,
	0xe6, 0x96, 0xcc, 0x40, 0x3a, 0xa3, 0x88, 0x70, 0x1e, 0x8c, 0x26, 0xce, 0x72, 0x56, 0x26, 0x22,
	0xee, 0xf1, 0x0e, 0x12, 0xd2, 0x83, 0xf2, 0x24, 0x07, 0xc7, 0x17, 0x11, 0x4c, 0x02, 0x3e, 0x01,
	0x6c, 0xac, 0xdd, 0x6f, 0xb5, 0x91, 0xa4, 0xf8, 0x32, 0x67, 0x65, 0x5a, 0xaf, 0x8f, 0x1f, 0x6a,
	0x25, 0xb5, 0x66, 0x27, 0x66, 0x86, 0xa2, 0x81, 0xd5, 0xa8, 0x62, 0x06, 0x97, 0xbd, 0x24, 0x4d,
	0x61, 0xab, 0x62, 0x1c, 0x13, 0x3f, 0xe7, 0x43, 0x64, 0x6f, 0xcd, 0x6e, 0x84, 0x8b, 0x08, 0x27,
	0xa1, 0x7e, 0x87, 0xe5, 0xab, 0x74, 0xf8, 0x06, 0xd7, 0xbf, 0x27, 0xc6, 0xfb, 0x93, 0x55, 0xc4,
	0x7e, 0xb3, 0x87, 0x7f, 0xaa, 0x2a, 0xce, 0xba, 0x55, 0x74, 0x3c, 0x7f, 0x07, 0x00, 0x00, 0xff,
	0xff, 0x76, 0xbe, 0x96, 0x6f, 0xb8, 0x01, 0x00, 0x00,
}
